PUPPETMASTER = '10.80.160.21'
USER = 'root'
SSH= 'ssh'

task :deploy do
sh "git pull origin master"
sh "#{SSH} #{USER}@#{PUPPETMASTER} 'cd /etc/puppet; git pull origin master; chown -R puppet:puppet /etc/puppet'"
end

task :cleandeploy do
sh "#{SSH} #{USER}@#{PUPPETMASTER} 'ssh -T -o StrictHostKeyChecking=no git@github.com;cd /etc/puppet; git init; git remote add origin git@github.com:moutai/Puppet-HPC-virtual-cluster-automation.git;git pull origin master;chown -R puppet:puppet /etc/puppet ; /etc/init.d/puppetmaster restart'"
end


task :softdeploy do
sh "#{SSH} #{USER}@#{PUPPETMASTER} 'cd /etc/puppet; git pull origin master'"
end

task :apply => [:deploy] do
client = ENV['CLIENT']
sh "#{SSH} #{USER}@#{client} 'puppet agent --test --verbose'" do |ok, status|
puts case status.exitstatus
when 0 then "Client is up to date."
when 1 then "Puppet couldn't compile the manifest."
when 2 then "Puppet made changes."
when 4 then "Puppet found errors."
end
end
end


task :softapply do
client = ENV['CLIENT']
sh "#{SSH} #{USER}@#{client} 'puppet agent --test --verbose'" do |ok, status|
puts case status.exitstatus
when 0 then "Client is up to date."
when 1 then "Puppet couldn't compile the manifest."
when 2 then "Puppet made changes."
when 4 then "Puppet found errors."
end
end
end



task :terminateallinstances do
sh "euca-describe-instances|grep -e 'INSTANCE'|awk -F \" \" '\{print \$2\}'| while read line; do euca-terminate-instances \$line ; done"
end

task :terminatependinginstances do
sh "euca-describe-instances|grep pending|grep -e 'INSTANCE'|awk -F \" \" '\{print \$2\}'| while read line; do euca-terminate-instances \$line ; done"
end


